# Stage 0: All
# =====================================================================================================================
FROM caddy:latest

COPY ./.docker/prod/proxy/Caddyfile /etc/caddy/Caddyfile

